### ISSUE TITLE
return nan when using imbalance estimate

### ISSUE THREAD

**Issue by mengysun** [lewisbails/cem#10]
* cem version:0.1.5
* Python version:3.8
* Operating System:linux

### Description
I try to follow the basic example of using the cem package on my data, however, I come across nan value when checking the imbalance of the data after matching (by the way, there is a warning message when running the code):
"python3.8/site-packages/cem/imbalance.py:28: RuntimeWarning: invalid value encountered in true_divide
  return np.sum(np.abs(l / np.sum(l) - r / np.sum(r))) / 2"
And subsequently when I try to generate match weight, there are no weights that are non-zero.
This is unlikely because my data is very large so it should be easy to construct match.
### What I Did
c.imbalance()
c.imbalance(schema) *this  code return nan value
weights = c.match(schema)
#all weights are zero.
```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by lewisbails** [comment]
Hi!

Thanks for opening an issue. Are you saying you get nan when doing the toy
example or using your data?

Perhaps you could try a simpler schema and see if it still returns nan for
your data. If you'd like to contribute a pull request fixing the problem if
there is one, that would be nice too.

**Comment by JewelHan** [comment]
Hi!

I have come across the same issue. All weights are zero after matching and the c.imbalance(schema) returns nan. 
I wander whether you have fixed the problem and how to deal with it. It would be very grateful if you could reply!

> * cem version:0.1.5
> * Python version:3.8
> * Operating System:linux
> 
> ### Description
> I try to follow the basic example of using the cem package on my data, however, I come across nan value when checking the imbalance of the data after matching (by the way, there is a warning message when running the code): "python3.8/site-packages/cem/imbalance.py:28: RuntimeWarning: invalid value encountered in true_divide return np.sum(np.abs(l / np.sum(l) - r / np.sum(r))) / 2" And subsequently when I try to generate match weight, there are no weights that are non-zero. This is unlikely because my data is very large so it should be easy to construct match.
> 
> ### What I Did
> c.imbalance() c.imbalance(schema) *this code return nan value weights = c.match(schema) #all weights are zero.
> 
> ```
> Paste the command(s) you ran and the output.
> If there was a crash, please include the traceback here.
> ```

**Comment by lewisbails** [comment]
Hi @JewelHan, thanks for commenting with your issue.
I'm only guessing but "nan" is telling me there may be a zero-division somewhere when using your schema to coarsen and calculate multidimensional imbalance. Can you please try a simpler schema and report back?
This is very much an open source project so I'm always open to pull requests should you like to contribute.

**Comment by JewelHan** [comment]
> This is very much an open source project so I'm always open to pull requests should you like to contribute.

The simpler schema I use is  as follows:

schema = {
   'age': ('cut', {'bins': 3}),
   'gender': ('cut', {'bins': 2}), 
   'amount': ('cut', {'bins': 5})
   }

'age' and 'gender' are variables of type int64. 'amount' is a variable of type float64.
However, the command c.imbalance(schema) still doesn't work and returns nan.

**Comment by lewisbails** [comment]
Thanks, are the data you're using open source? I would like to try reproduce the error.
Otherwise I'd be happy to look at a pull request if you want to contribute.

**Comment by JewelHan** [comment]
Hi!

I have reproduced the error with the data from an open source. The data is attached as follows. 
[data.csv](https://github.com/lewisbails/cem/files/9597343/data.csv)

The variable PUSH indicates whether the sample is in  treatment group (if equals 1) or control group (if equals 0).  ACTIVE_LEVEL is the outcome variable.


The schema I use is as follows:

schema = {
   'AGE': ('cut', {'bins': 3}),
   'SEX': ('cut', {'bins': 2}),
   'VIP_LEVEL': ('cut', {'bins': 4})
   }

**Comment by lewisbails** [comment]
This is happening because none of the resulting strata had all levels of the treatment variable. This happens because you aren't coarsening one or more continuous variables. For example "ID" in your dataset is unique, so leaving it uncoarsened will in a single example in each strata, thus no strata can have each level of the treatment.
I recommend dropping columns you don't want to define your strata with and add the remaining continuous variables to the coarsening schema.

I have added some checks and warnings when the user had provided such incomplete coarsening schemas. See the 0.1.7 release.

Thanks for raising the issue!
