### ISSUE TITLE
Issue with relax.cem() function in R

### ISSUE THREAD

**Issue by 49470952** [lewisbails/cem#12]
* cem version: 1.1.31
* Python version:
* Operating System:

### Description

By running the relax.cem function, I received the error below (R code 1).

### What I Did
I played with the 'perc' parameter, and found when it decreased to 0.6, I was able to get rid of the error.
I also tried to use different combination of covariates, for some of the combinations, there's no error.

The covariates included in the depression_2[,var2] includes treated, age, healthcare spending, number of doctor visits as well as some medical conditions (0/1). They were all coded as numeric variables. 

Can someone please let me know what caused the error? it seems to me the covariates combinations may have some contribution (not sure how), and there might be something else. Any input will be greatly appreciated!! Thanks!

R code 1:
mat <- cem(treatment = "treated", data = depression_2[,var2],keep.all=TRUE )  
mat_2 <- relax.cem(mat, depression_2[,var2],depth=1, perc=0.8 )
    ****Error in xy.coords(x, y, xlabel, ylabel, log) : 
  'x' and 'y' lengths differ**

R code 2:
mat <- cem(treatment = "treated", data = depression_2[,var2],keep.all=TRUE )  
mat_2 <- relax.cem(mat, depression_2[,var2],depth=1, perc=0.6 )

**Comment by lewisbails** [comment]
I think you might have the wrong package. Perhaps you were looking for [this](https://github.com/cran/cem) one?
