### ISSUE TITLE
Library is not working

### ISSUE THREAD

**Issue by njwagter0** [lewisbails/cem#23]
* cem version: just downloaded today
* Python version: 3.8
* Operating System: mac
* 

### Description

Use this for cem

### What I Did

from cem.match import match
from cem.coarsen import coarsen
from cem import L1, L2

non of these functions or libraries will import 

EX --> ModuleNotFoundError: No module named 'cem.match'

**Comment by lewisbails** [comment]
Apologies for the confusion, the imports for the functions `match`, `coarsen` and `L1`/`L2`  in `1.0.0` are:

```python
from cem import match
from cem import coarsen
from cem.imbalance import L1, L2
```

You could also use:
```python
from cem.match import match
from cem.coarsen import coarse
```
for those functions

But I understand the confusion and will update the package to be more clear.

**Comment by lewisbails** [comment]
Please see the latest release that addresses your problem:
https://github.com/lewisbails/cem/releases/tag/1.1.0
