### ISSUE TITLE
this blocks users with Python < 3.7. Is there anyway we can make it optional?

### ISSUE THREAD

**Issue by JaneEvans** [lewisbails/cem#6]
https://github.com/lewisbails/cem/blob/66f5e796f1fdce39c1ebc7247c7943efa9f855e1/cem/cem.py#L1

**Comment by lewis-bails** [comment]
Hey @JaneEvans, thanks for checking out CEM.
If you wanted to create a pull request for this then feel free! Unfortunately I don't have much time these days to put work into the package.
